#!/bin/bash

get_current_user() {
    az account show --query user.name -o tsv
}

get_access_token() {
    az account get-access-token --resource https://ossrdbms-aad.database.windows.net --query accessToken -o tsv
}

# Usage: ./script.sh <host> <dbname> [user]
if [ "$#" -lt 2 ] || [ "$#" -gt 3 ]; then
    echo "Usage: $0 <host> <dbname> [user]"
    exit 1
fi

HOST=$1
DBNAME=$2

if [ "$#" -eq 3 ]; then
    USER="$3"
else
    USER=$(get_current_user)
    if [ $? -ne 0 ]; then
        echo "Error retrieving current Azure user."
        exit 1
    fi
fi

ACCESS_TOKEN=$(get_access_token)
if [ $? -ne 0 ]; then
    echo "Error retrieving access token."
    exit 1
fi

export PGPASSWORD="$ACCESS_TOKEN"
export PGSSLMODE=require

psql -h "$HOST" -d "$DBNAME" -U "$USER"
if [ $? -ne 0 ]; then
    echo "Error connecting to the database."
    exit 1
fi
