#!/bin/bash

# Display a welcoming message
printf "\033[1;34mWelcome to \033[1;33mcli-tools\033[0m\n"
printf "\033[1;34mListing executable files...\033[0m\n\n"

# Get the directory of the currently executing script
dir=$(dirname "$0")

# List only the executable files in that directory
ls -l "$dir" | awk '/^-..x/ {print $NF}' | while read -r file; do
	printf "\033[1;33m$file\033[0m\n"
done
printf "\n"
